languageCode: 'fr'
baseURL: localhost
removePathAccents: true

params:
  contact:
    email:
      content: proust@arthaud.dev
      prefix: "mailto:"
  seo:
    author: Jhon Doe
    title: Page - Site name
    desc: "Meaningful page description - Site name"
    subject: "subject of website"
    url: localhost
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png
    links:
      facebook: https://www.facebook.com/username
      instagram: https://www.instagram.com/username
      linkedin: https://www.linkedin.com/in/username


related:
  indices:
    - name: bonne-pratiques # The name of the indice, same as Front Matter's .Param key.
      weight: 1 # We don't really need this, but omitting it would disable the indice.
      includeNewer: true