languageCode: 'fr'
baseURL: /
removePathAccents: true

params:
  seo:
    author: MMI Bordeaux
    title: Profitez du numérique en toute sécurité
    desc: "Découvrez les bonnes pratiques en cybersécurité grâce à un quizz fait pour le grand public - Safe N Tech"
    subject: "security"
    url: https://safe-n-tech.netlify.app
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png
    links:
      facebook: https://www.facebook.com/username
      instagram: https://www.instagram.com/username
      linkedin: https://www.linkedin.com/in/username

taxonomies:
  # disable all taxonomies

permalinks:
  thematiques: /:section/:title/
  vulnerabilities: /:section/:title/
  good-practices: /:section/:title/


menu:
  header:
    - identifier: thematiques
      weight: 1
      name: Thématiques
      title: thématiques
      url: /thematiques/
    - identifier: quizz
      weight: 2
      name: Quiz
      title: quiz
      url: /quizz/
    - identifier: good-practices
      weight: 3
      name: Bonnes pratiques
      title: bonnes pratiques
      url: /good-practices/
    - identifier: vulnerabilities
      weight: 4
      name: Vulnérabilités
      title: vulnérabilités
      url: /vulnerabilities/
    - identifier: definitions
      weight: 5
      name: Glossaire
      title: glossaire
      url: /definitions/
