languageCode: 'fr'
baseURL: https://cybersecu-app.netlify.app
removePathAccents: true

params:
  seo:
    author: MMI Bordeaux
    title: Profitez du numérique en toute sécurité
    desc: "Découvrez les bonnes pratiques en cybersécurité grâce à un quizz fait pour le grand public - Safe N Tech"
    subject: "security"
    url: https://cybersecu-app.netlify.app
    hero: /sprites/hero-min.jpg
    logo: /sprites/logo-min.png
    links:
      facebook: https://www.facebook.com/username
      instagram: https://www.instagram.com/username
      linkedin: https://www.linkedin.com/in/username

taxonomies:
  # disable all taxonomies

permalinks:
  thematiques: /:section/:title/
  vulnerabilities: /:section/:title/
  good-practices: /:section/:title/


menu:
  header:
    - identifier: good-practices
      name: Bonnes pratiques
      title: bonnes pratiques
      url: /good-practices
    - identifier: quizz
      name: Quiz
      title: quiz
      url: /quizz
    - identifier: thematiques
      name: Thématiques
      title: thématiques
      url: /thematiques
    - identifier: definitions
      name: Glossaire
      title: glossaire
      url: /definitions
