[build]
publish = "public"
command = "npm run build"

[[redirects]]
  from = "http://cybersecu-app.netlify.app/*"
  to = "https://safe-n-tech.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://cybersecu-app.netlify.app/*"
  to = "https://safe-n-tech.netlify.app/:splat"
  status = 301
  force = true