backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: categories
    label: Catégories
    label_singular: Catégorie
    folder: content/categories
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Titre, name: title }

  - name: vulnerabilities
    label: Vulnérabilités
    label_singular: Vulnérabilités
    folder: content/vulnerabilities
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    view_groups:
      - label: Catégorie
        field: categories
    view_filters:
      - label: Boîte mail
        field: categories
        pattern: Boîte mail
      - label: Déplacements
        field: categories
        pattern: Déplacements
      - label: Données confidentielles
        field: categories
        pattern: Données confidentielles
      - label: Droit résiduel à la vie privée
        field: categories
        pattern: Droit résiduel à la vie privée
      - label: Mise à jour
        field: categories
        pattern: Mise à jour
      - label: Mots de passe
        field: categories
        pattern: Mots de passe
      - label: Paiement en ligne
        field: categories
        pattern: Paiement en ligne
      - label: Réseaux sociaux
        field: categories
        pattern: Réseaux sociaux
      - label: Téléchargements et ingénierie sociale
        field: categories
        pattern: Téléchargements et ingénierie sociale
      - label: Wifi et bluetooth
        field: categories
        pattern: Wifi et bluetooth
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }
      - { label: Titre, name: title }
      - {
          label: Catégorie,
          name: categories,
          widget: relation,
          collection: categories,
          search_fields: ["title"],
          value_field: "title",
      }
      - {
        label: Risques,
        name: risks,
        widget: list,
        required: false
      }
      - {
        label: Bonnes pratiques,
        name: goodPractices,
        widget: relation,
        collection: good-practices,
        search_fields: [ "title" ],
        value_field: "title",
        multiple: true,
        required: false
      }
      - {
        label: Définitions,
        name: definitions,
        widget: relation,
        collection: definitions,
        search_fields: [ "title" ],
        value_field: "title",
        multiple: true,
        required: false
      }

  - name: good-practices
    label: Bonnes pratiques
    label_singular: Bonne pratique
    folder: content/good-practices
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    view_groups:
      - label: Catégorie
        field: categories
    view_filters:
      - label: Boîte mail
        field: categories
        pattern: Boîte mail
      - label: Déplacements
        field: categories
        pattern: Déplacements
      - label: Données confidentielles
        field: categories
        pattern: Données confidentielles
      - label: Droit résiduel à la vie privée
        field: categories
        pattern: Droit résiduel à la vie privée
      - label: Mise à jour
        field: categories
        pattern: Mise à jour
      - label: Mots de passe
        field: categories
        pattern: Mots de passe
      - label: Paiement en ligne
        field: categories
        pattern: Paiement en ligne
      - label: Réseaux sociaux
        field: categories
        pattern: Réseaux sociaux
      - label: Téléchargements et ingénierie sociale
        field: categories
        pattern: Téléchargements et ingénierie sociale
      - label: Wifi et bluetooth
        field: categories
        pattern: Wifi et bluetooth
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }
      - { label: Titre, name: title }
      - {
        label: Catégorie,
        name: categories,
        widget: relation,
        collection: categories,
        search_fields: [ "title" ],
        value_field: "title",
      }
      - {
        label: Définitions,
        name: definitions,
        widget: relation,
        collection: definitions,
        search_fields: [ "title" ],
        value_field: "title",
        multiple: true,
        required: false
      }
      - { label: 'Contenu', name: 'body', widget: 'markdown', required: false }

  - name: definitions
    label: Définitions
    label_singular: Définition
    folder: content/definitions
    create: true
    editor: { preview: false }
    filter: { field: "visibleInCms", value: true }
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true }
      - { label: Titre, name: title }
      - { label: 'Contenu', name: 'body', widget: 'markdown', required: false }